// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/linked-list/list-3-circular.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/linked-list/list-99-summary.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/linked-list/list-1-single.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/linked-list/list-2-doubly.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/linked-list/list-9-usage1.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/linked-list/list-0-index.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/map/map-0-index.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/set/set-0-index.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/tree-3-redblack.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/map/map-1-impl.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/map/map-2-hash.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/set/set-1-impl.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/tree-1-binary.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/tree-0-intro.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/calculation/complexity.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/tree-2-AVL.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/calculation/search.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/graph-0.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/graph-1.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/graph-2.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/tree-graph/graph-3.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/calculation/index.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/calculation/mode.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/calculation/sort.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/index.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/queue.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/foundation/stack.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/index.en-US.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/docs/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/foundation/linked-list/list-3-circular': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/foundation/linked-list/list-99-summary': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/foundation/linked-list/list-1-single': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/foundation/linked-list/list-2-doubly': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/foundation/linked-list/list-9-usage1': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/foundation/linked-list/list-0-index': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/foundation/map/map-0-index': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/foundation/set/set-0-index': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/tree-graph/tree-3-redblack': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/foundation/map/map-1-impl': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/foundation/map/map-2-hash': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/foundation/set/set-1-impl': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/tree-graph/tree-1-binary': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/tree-graph/tree-0-intro': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/calculation/complexity': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/tree-graph/tree-2-AVL': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/calculation/search': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/tree-graph/graph-0': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/tree-graph/graph-1': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/tree-graph/graph-2': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/tree-graph/graph-3': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/calculation/index': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/calculation/mode': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/calculation/sort': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/foundation/index': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/foundation/queue': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/foundation/stack': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/index.en-US': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/index': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
