// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/admin/wujunfeng/codes/frontend/github/data-structures-js/node_modules/_dumi@2.1.5@dumi/theme-default/slots/NotFound/index.js';
